// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.View
{
    public partial class vw_CostManage_CostOfMonth
    {
        public int CostDetailID { get; set; }
        [Required]
        [StringLength(50)]
        public string CostDetailName { get; set; }
        public double EstimateCostDetail { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        public double? CostValue { get; set; }
        public double? Diff { get; set; }
    }
}