// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.View
{
    //[Keyless]
    public partial class vw_CostEmploy
    {
        [StringLength(8000)]
        public string BillCode { get; set; }
        [Required]
        [StringLength(19)]
        public string RetailName { get; set; }
        [Required]
        [StringLength(24)]
        public string Address { get; set; }
        [Required]
        [StringLength(12)]
        public string Hotline { get; set; }
        [Required]
        [StringLength(17)]
        public string AccountName { get; set; }
        [StringLength(61)]
        public string DateTimeCreate { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        [Required]
        [StringLength(7)]
        public string CostEmploy { get; set; }
        public int? DaysInMonth { get; set; }
        [StringLength(2)]
        public string WorkDays { get; set; }
        public int? OffDays { get; set; }
        [StringLength(4000)]
        public string Total { get; set; }
    }
}