// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.View
{
    public partial class vw_CostManage_Transaction
    {
        public int TransactionID { get; set; }
        public int CostDetailID { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateOfMonth { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public double CostValue { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        public int Position { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTimeCreate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateTimeUpdate { get; set; }
        [StringLength(50)]
        public string CostDetailName { get; set; }
    }
}