// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.View
{
    //[Keyless]
    public partial class vw_ChartIncome
    {
        public int Month { get; set; }
        public int Year { get; set; }
        [StringLength(22)]
        public string Time { get; set; }
        public double? Weight { get; set; }
        public double? IntoMoney { get; set; }
        public double? Remain { get; set; }
        public double? CostEmploy { get; set; }
    }
}