// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.View
{
    public partial class vw_CostManage_CostDetail
    {
        public int CostDetailID { get; set; }
        public int? GroupCostID { get; set; }
        [StringLength(50)]
        public string GroupCostName { get; set; }
        public double? EstimateGroupCost { get; set; }
        [StringLength(500)]
        public string DescriptGroupCost { get; set; }
        [Required]
        [StringLength(50)]
        public string CostDetailName { get; set; }
        public double EstimateCostDetail { get; set; }
        [Required]
        [StringLength(1000)]
        public string DescriptCostDetail { get; set; }
    }
}