// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.View
{
    public partial class vw_MoneyRenewal
    {
        public long? STT { get; set; }
        public int ID { get; set; }
        [StringLength(50)]
        public string Address { get; set; }
        [Required]
        [StringLength(50)]
        public string FullName { get; set; }
        [Required]
        [StringLength(1)]
        public string Code { get; set; }
        [Required]
        [StringLength(1)]
        public string Stage { get; set; }
        [Required]
        [StringLength(1)]
        public string Month { get; set; }
        [Required]
        [StringLength(1)]
        public string Year { get; set; }
        public double Money { get; set; }
        public double Postage { get; set; }
        public double Total { get; set; }
        public int ServiceID { get; set; }
        [StringLength(50)]
        public string ServiceName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTimeAdd { get; set; }
        [Required]
        [StringLength(1)]
        public string BankID { get; set; }
        [Required]
        [StringLength(1)]
        public string BankName { get; set; }
        public int RetailID { get; set; }
        [StringLength(200)]
        public string RetailName { get; set; }
        [StringLength(200)]
        public string DeputizeName { get; set; }
        [StringLength(10)]
        public string Hotline { get; set; }
        [StringLength(200)]
        public string AddressRetail { get; set; }
    }
}