// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.View
{
    public class vw_MonthlyTransactionTemp
    {
        public long? STT { get; set; }
        public int ID { get; set; }
        public int ServiceID { get; set; }
        [StringLength(50)]
        public string ServiceName { get; set; }
        public int CustomerID { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        public int RetailID { get; set; }
        [StringLength(200)]
        public string RetailName { get; set; }
        public int? BankID { get; set; }
        [StringLength(50)]
        public string BankName { get; set; }
        public int Money { get; set; }
        public int Postage { get; set; }
        public int Total { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTimeAdd { get; set; }
    }
}