// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.View
{
    public partial class vw_PieChart
    {
        public long? STT { get; set; }
        public int RetailID { get; set; }
        [StringLength(200)]
        public string RetailName { get; set; }
        public int? Money { get; set; }
        public int? Postage { get; set; }
        public int? Total { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        [StringLength(22)]
        public string Time { get; set; }
    }
}