// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GenModel
{
    public partial class fn_dataCostAndIncomeByMonthResult
    {
        public int? STT { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        public string Time { get; set; }
        public double? Income { get; set; }
        public double? EstimateIncome { get; set; }
        public double? Cost { get; set; }
        public double? EstimateCost { get; set; }
        public double? Diff { get; set; }
        public double? Saved { get; set; }
    }
}
