// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.Table
{
    [Table("MoneyTransfer")]
    public partial class MoneyTransfer
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string FullName { get; set; }
        [Required]
        [StringLength(20)]
        public string Code { get; set; }
        public int ServiceID { get; set; }
        public int Money { get; set; }
        public int Postage { get; set; }
        public int Total { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTimeAdd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateTimeUpdate { get; set; }
        public int? BankID { get; set; }
        public int RetailID { get; set; }
    }
}