// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.Table
{
    [Table("Option")]
    public partial class Option
    {
        [Key]
        public int OptionID { get; set; }
        [StringLength(500)]
        public string OptionKey { get; set; }
        [StringLength(500)]
        public string OptionValue { get; set; }
    }
}