// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.Table
{
    [Table("Retail")]
    public partial class Retail
    {
        [Key]
        public int RetailID { get; set; }
        [Required]
        [StringLength(200)]
        public string RetailName { get; set; }
        [Required]
        [StringLength(200)]
        public string DeputizeName { get; set; }
        [StringLength(10)]
        public string Hotline { get; set; }
        [Required]
        [StringLength(200)]
        public string Address { get; set; }
    }
}