// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SystemServiceAPI.Entities.Table
{
    public partial class Service
    {
        [Key]
        public int ServiceID { get; set; }
        [Required]
        [StringLength(50)]
        public string ServiceName { get; set; }
        public bool IsDelete { get; set; }
    }
}